```{r}
library(tidyverse)
library(haven)
dat <- read_sav("W110_Jun22/ATP W110.sav")
dat1 <- read_sav("W110_Jun22/ATP W110.sav")
altdat <- read_sav("W52_Jul19/ATP W52.sav")
altdat1 <- read_sav("W52_Jul19/ATP W52.sav")
```

```{r}
dat <- dat |>
  mutate(
    Party = if_else(PARTY_W110 == 1, "Republican", "Democrat"), 
    Approval = if_else(POL1JB_W110 == 1, "Approve", "Disapprove"),
    Gender = if_else(F_GENDER == 1, "Man", "Woman"),
    Age = if_else(
      F_AGECAT == 1, "18-29",
      if_else(F_AGECAT == 2, "30-49",
        if_else(F_AGECAT == 3, "50-64",
          if_else(F_AGECAT == 4, "65+", "N/A")))))
```

```{r}
altdat <- 
  altdat |>
  mutate(
    Party = if_else(F_PARTY_FINAL == 1, "Republican", "Democrat"), 
    Gender = if_else(F_SEX == 1, "Man", "Woman"),
    Approval = if_else(POL1DT_W52 == 1, "Approve", "Disapprove"), 
    Age = if_else(
      F_AGECAT == 1, "18-29",
      if_else(F_AGECAT == 2, "30-49",
        if_else(F_AGECAT == 3, "50-64",
          if_else(F_AGECAT == 4, "65+", "N/A")))))
```
```{r}
# Combine the two datasets
combined_data <- bind_rows(
  mutate(dat, dataset = "W110_Jun22"),
  mutate(altdat, dataset = "W52_Jul19")
)

# Create a summary similar to your previous code
summary_data <- combined_data |>
  group_by(Approval, Party, Gender, dataset) |>
  summarize(count = n()) |>
  mutate(altmean = count / sum(count))

print(summary_data)


```

```{r}
# Bar plot
ggplot(summary_data, aes(x = Approval, y = altmean, fill = Party)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(rows = vars(Gender), cols = vars(dataset)) +
  labs(title = "Approval Ratings by Party, Gender, and Dataset",
       x = "Approval",
       y = "Proportion")
```



